# Generated by Django 5.2.17 on 2026-10-01 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.carro'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.sector'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.sector'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarro',
            unique_together={('carro', 'sector')},
        ),
    ]
